#Requires -Version 5.1
<#
.SYNOPSIS
    Downloads HIBP NTLM password hashes and compresses them to a binary file.

.DESCRIPTION
    1. Reads paths from config.psd1 (generated by PrepareEnv.ps1).
    2. Reads runtime settings from settings.json (user-editable, optional).
    3. Downloads all NTLM hashes with haveibeenpwned-downloader (64 threads,
       overwrite enabled).  Output streamed live to console + log.
    4. Converts the resulting text file to a packed binary using pypsirepacker
       (Python, streaming, near-zero memory).
    5. Final binary is saved as  hibpntlmhashes<ddMMyy>.bin  in OutputPath.

    Command-line parameters override settings.json values.

.PARAMETER OutputPath
    Directory for the final .bin file. Overrides settings.json OutputPath.
    Default: output\bin\ (from config.psd1).

.PARAMETER Parallelism
    Download thread count for haveibeenpwned-downloader.
    Overrides settings.json Parallelism. Default: 64.

.PARAMETER NoOverwrite
    Pass to skip -o flag for the downloader (do not overwrite existing ranges).

.PARAMETER SkipDownload
    Skip download if hash text file already exists.

.PARAMETER KeepHashFile
    Do not delete the source text file after packing.
    Overrides settings.json KeepHashFile.

.EXAMPLE
    .\BinaryCreator.ps1

.EXAMPLE
    .\BinaryCreator.ps1 -OutputPath 'D:\HIBP'

.EXAMPLE
    .\BinaryCreator.ps1 -SkipDownload -Parallelism 32
#>

[CmdletBinding()]
param(
    [string]$OutputPath,
    [int]   $Parallelism,
    [switch]$NoOverwrite,
    [switch]$SkipDownload,
    [switch]$KeepHashFile
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# -----------------------------------------------------------------------------
#  Load shared helpers
# -----------------------------------------------------------------------------
. (Join-Path $PSScriptRoot 'lib\HIBPBinCreator.Helpers.ps1')

# -----------------------------------------------------------------------------
#  Load config
# -----------------------------------------------------------------------------

$configPath = Join-Path $PSScriptRoot 'config.psd1'

if (-not (Test-Path $configPath)) {
    Write-Host '[WARN]  config.psd1 not found - running PrepareEnv.ps1 first...' -ForegroundColor Yellow
    $prepareScript = Join-Path $PSScriptRoot 'PrepareEnv.ps1'
    if (-not (Test-Path $prepareScript)) {
        Write-Host "[ERROR] PrepareEnv.ps1 not found at: $prepareScript" -ForegroundColor Red
        exit 1
    }
    & $prepareScript
    if ($LASTEXITCODE -ne 0) {
        Write-Host '[ERROR] PrepareEnv.ps1 failed. Cannot continue.' -ForegroundColor Red
        exit 1
    }
    if (-not (Test-Path $configPath)) {
        Write-Host '[ERROR] PrepareEnv.ps1 completed but config.psd1 was not created.' -ForegroundColor Red
        exit 1
    }
    Write-Host '[SUCCESS] Environment ready - continuing with BinaryCreator.' -ForegroundColor Green
}

$cfg = Import-PowerShellDataFile -Path $configPath

# -----------------------------------------------------------------------------
#  Load settings.json (user-editable runtime settings)
# -----------------------------------------------------------------------------
$settingsPath = Join-Path $PSScriptRoot 'settings.json'
$settings = @{}
if (Test-Path $settingsPath) {
    try {
        $settingsJson = Get-Content $settingsPath -Raw
        # Allow Windows paths with single backslashes (e.g. "D:\test\output")
        # by escaping lone backslashes before JSON parsing
        $settingsJson = $settingsJson -replace '\\(?!["\\/bfnrtu])', '\\'
        $settings = @{}
        $parsed = $settingsJson | ConvertFrom-Json
        foreach ($prop in $parsed.PSObject.Properties) {
            $settings[$prop.Name] = $prop.Value
        }
    } catch {
        Write-Host "[WARN]  Failed to read settings.json: $_" -ForegroundColor Yellow
    }
}

# Merge: command-line params > settings.json > defaults
# Parallelism: CLI > settings > 64
if (-not $PSBoundParameters.ContainsKey('Parallelism')) {
    if ($settings.ContainsKey('Parallelism') -and $settings.Parallelism) {
        $Parallelism = [int]$settings.Parallelism
    } else {
        $Parallelism = 64
    }
}

# KeepHashFile: CLI > settings > $false
if (-not $PSBoundParameters.ContainsKey('KeepHashFile')) {
    if ($settings.ContainsKey('KeepHashFile') -and $settings.KeepHashFile -eq $true) {
        $KeepHashFile = [switch]::new($true)
    }
}

# NoOverwrite: CLI > settings > $false
if (-not $PSBoundParameters.ContainsKey('NoOverwrite')) {
    if ($settings.ContainsKey('NoOverwrite') -and $settings.NoOverwrite -eq $true) {
        $NoOverwrite = [switch]::new($true)
    }
}

# SkipDownload: CLI > settings > $false
if (-not $PSBoundParameters.ContainsKey('SkipDownload')) {
    if ($settings.ContainsKey('SkipDownload') -and $settings.SkipDownload -eq $true) {
        $SkipDownload = [switch]::new($true)
    }
}

# OutputPath: CLI > settings > config BinDir
if (-not $PSBoundParameters.ContainsKey('OutputPath') -or [string]::IsNullOrWhiteSpace($OutputPath)) {
    if ($settings.ContainsKey('OutputPath') -and -not [string]::IsNullOrWhiteSpace($settings.OutputPath)) {
        $OutputPath = $settings.OutputPath
    }
}

# Safe config access helper (StrictMode-compatible for missing keys)
function Get-CfgValue {
    param([hashtable]$Cfg, [string]$Key, [string]$Default = '')
    if ($Cfg.ContainsKey($Key)) { return $Cfg[$Key] }
    return $Default
}

$HashesDir      = Get-CfgValue $cfg 'HashesDir'  (Join-Path $PSScriptRoot 'output\hashes')
$BinDir         = if ($OutputPath) { $OutputPath } else { Get-CfgValue $cfg 'BinDir' (Join-Path $PSScriptRoot 'output\bin') }
$LogsDir        = Get-CfgValue $cfg 'LogsDir'   (Join-Path $PSScriptRoot 'logs')
$DotnetToolsDir = Get-CfgValue $cfg 'DotnetToolsDir' (Join-Path $PSScriptRoot 'tools')

# Ensure output directory exists
if (-not (Test-Path $BinDir)) {
    New-Item -ItemType Directory -Path $BinDir -Force | Out-Null
}

# Ensure dotnet tools folder is on PATH
if ($DotnetToolsDir -and $env:PATH -notlike "*$DotnetToolsDir*") {
    $env:PATH += ";$DotnetToolsDir"
}

# Resolve Python path from config (may be missing in old config files)
$pythonExe = Get-CfgValue $cfg 'PythonExe'

# -----------------------------------------------------------------------------
#  Logging
# -----------------------------------------------------------------------------
$RunTimestamp    = Get-Date -Format 'yyyyMMdd_HHmmss'
$script:LogFile = Join-Path $LogsDir "BinaryCreator_$RunTimestamp.log"

# -----------------------------------------------------------------------------
#  Validate prerequisites
# -----------------------------------------------------------------------------
Write-Step 'Validating prerequisites'

$hibpExe = Get-Command 'haveibeenpwned-downloader.exe' -ErrorAction SilentlyContinue
if (-not $hibpExe) {
    $hibpExe = Get-Command 'haveibeenpwned-downloader' -ErrorAction SilentlyContinue
}
if (-not $hibpExe) {
    Write-Log 'haveibeenpwned-downloader not found on PATH.' -Level ERROR
    Write-Log "Ensure PrepareEnv.ps1 was run and '$DotnetToolsDir' is on PATH." -Level ERROR
    exit 1
}
Write-Log "haveibeenpwned-downloader : $($hibpExe.Source)" -Level SUCCESS

# Validate Python
if (-not $pythonExe -or -not (Test-Path $pythonExe)) {
    $pyInfo = Test-PythonAvailable
    if ($pyInfo) {
        $pythonExe = $pyInfo.ExePath
    } else {
        Write-Log 'Python 3.6+ not found. Re-run PrepareEnv.ps1 or install Python.' -Level ERROR
        exit 1
    }
}
Write-Log "Python                    : $pythonExe" -Level SUCCESS

# -----------------------------------------------------------------------------
#  File paths
# -----------------------------------------------------------------------------
$DateSuffix   = Get-Date -Format 'ddMMyy'
$HashBaseName = 'pwnedpasswords_ntlm'
$HashFile     = Join-Path $HashesDir "${HashBaseName}.txt"
$BinFileName  = "hibpntlmhashes${DateSuffix}.bin"
$BinFile      = Join-Path $BinDir $BinFileName

Write-Log "Hash text file : $HashFile"
Write-Log "Binary output  : $BinFile"
Write-Log "Log file       : $script:LogFile"

# -----------------------------------------------------------------------------
#  Disk space pre-check
# -----------------------------------------------------------------------------
$MinFreeGB        = 100
$driveLetter      = (Split-Path -Qualifier $HashesDir).TrimEnd(':')
$driveInfo        = Get-PSDrive -Name $driveLetter -ErrorAction SilentlyContinue
$freeBytes        = if ($driveInfo) { $driveInfo.Free } else { 0 }
$freeGB           = [math]::Round($freeBytes / 1GB, 1)

if (-not $SkipDownload) {
    if ($freeGB -lt $MinFreeGB) {
        Write-Log "Disk space check: ${freeGB} GB free on ${driveLetter}: drive - minimum ${MinFreeGB} GB recommended." -Level ERROR
        Write-Log "Free up space or change the output location before proceeding." -Level ERROR
        exit 1
    }
    Write-Log "Disk space check: ${freeGB} GB free on ${driveLetter}: (minimum ${MinFreeGB} GB) - OK" -Level SUCCESS
} else {
    Write-Log "Disk space: ${freeGB} GB free on ${driveLetter}: (skipping strict check - download skipped)"
}

# -----------------------------------------------------------------------------
#  Step 1 - Download NTLM hashes
# -----------------------------------------------------------------------------
Write-Step "Step 1/2 - Downloading NTLM hashes  (parallelism: $Parallelism)"

$dlElapsed = [timespan]::Zero

if ($SkipDownload -and (Test-Path $HashFile)) {
    $hashSize = (Get-Item $HashFile).Length
    Write-Log "-SkipDownload specified and hash file already exists - skipping download." -Level SUCCESS
    Write-Log "Hash file size : $(Format-Bytes $hashSize)  ($hashSize bytes)"
} else {
    if ($SkipDownload) {
        Write-Log '-SkipDownload specified but hash file not found - downloading anyway.' -Level WARN
    }

    $overwriteFlag = if ($NoOverwrite) { @() } else { @('-o') }
    $downloadArgs  = @('-n', $HashBaseName) + $overwriteFlag + @('-p', $Parallelism.ToString())
    $downloadCmd   = "haveibeenpwned-downloader $($downloadArgs -join ' ')"

    Write-Log "Changing working directory to: $HashesDir"
    Write-Log "Executing: $downloadCmd"
    Write-Log ''

    $dlStart    = [datetime]::UtcNow
    $dlExitCode = 0

    Push-Location $HashesDir
    try {
        & $hibpExe.Source @downloadArgs 2>&1 | ForEach-Object {
            $line = $_.ToString()
            $ts   = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
            Add-Content -Path $script:LogFile -Value "[$ts] [HIBP]   $line"
            Write-Host "  $line" -ForegroundColor DarkCyan
        }
        $dlExitCode = $LASTEXITCODE
    } finally {
        Pop-Location
    }

    $dlElapsed = [datetime]::UtcNow - $dlStart

    if ($dlExitCode -ne 0) {
        Write-Log "haveibeenpwned-downloader exited with code $dlExitCode." -Level ERROR
        exit $dlExitCode
    }

    if (-not (Test-Path $HashFile)) {
        Write-Log "Expected hash file not found after download: $HashFile" -Level ERROR
        Write-Log 'The downloader may have used a different output path. Check the hashes directory.' -Level WARN
        exit 1
    }

    $hashSize = (Get-Item $HashFile).Length
    Write-Log ''
    Write-Log "Download complete in $(Format-Elapsed $dlElapsed)." -Level SUCCESS
    Write-Log "Hash file size : $(Format-Bytes $hashSize)  ($hashSize bytes)" -Level SUCCESS
}

# -----------------------------------------------------------------------------
#  Step 2 - Compress to binary with pypsirepacker
# -----------------------------------------------------------------------------
Write-Step "Step 2/2 - Compressing to binary  ($BinFileName)"

Write-Log "Input  : $HashFile"
Write-Log "Output : $BinFile"
Write-Log "Tool   : $pythonExe -m pypsirepacker"
Write-Log ''

$packStart = [datetime]::UtcNow

$parentDir = $PSScriptRoot
$pyArgs = @('-c',
    "import sys; sys.path.insert(0, r'$parentDir'); from pypsirepacker.repacker import repack; repack(r'$HashFile', r'$BinFile')"
)

& $pythonExe @pyArgs 2>&1 | ForEach-Object {
    $line = $_.ToString()
    $ts   = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    Add-Content -Path $script:LogFile -Value "[$ts] [PyPSI]  $line"
    Write-Host "  $line" -ForegroundColor DarkGray
}

$packExitCode = $LASTEXITCODE
if ($packExitCode -ne 0) {
    Write-Log "pypsirepacker exited with code $packExitCode." -Level ERROR
    exit $packExitCode
}

$packElapsed = [datetime]::UtcNow - $packStart

if (-not (Test-Path $BinFile)) {
    Write-Log "Expected binary not found after packing: $BinFile" -Level ERROR
    exit 1
}

$binSize = (Get-Item $BinFile).Length

# -----------------------------------------------------------------------------
#  Sanity-check the binary, then remove the source text file
# -----------------------------------------------------------------------------

# Minimum expected binary size: 10% of source
$minExpectedSize = [long]($hashSize * 0.10)

if ($binSize -lt $minExpectedSize) {
    Write-Log "Binary sanity check FAILED: output is $(Format-Bytes $binSize) which is less than 10% of source $(Format-Bytes $hashSize)." -Level ERROR
    Write-Log "The binary may be corrupt. Hash text file has NOT been deleted: $HashFile" -Level WARN
    exit 1
}

Write-Log "Binary sanity check passed: $(Format-Bytes $binSize) from $(Format-Bytes $hashSize) source." -Level SUCCESS

# Remove the source hash text file now that the binary is confirmed good
if ($KeepHashFile) {
    Write-Log "-KeepHashFile specified - preserving source hash text file: $HashFile" -Level INFO
} else {
    Write-Log "Removing source hash text file: $HashFile"
    try {
        Remove-Item -Path $HashFile -Force
        Write-Log "Hash text file removed successfully." -Level SUCCESS
    } catch {
        Write-Log "Failed to remove hash text file: $_" -Level WARN
        Write-Log "You can delete it manually: $HashFile" -Level WARN
    }
}

# -----------------------------------------------------------------------------
#  Summary
# -----------------------------------------------------------------------------
Write-Step 'Completed'

Write-Log "Packing complete in $(Format-Elapsed $packElapsed)." -Level SUCCESS
Write-Log ''
Write-Log '  ---Output ------------------------------------------------------'
Write-Log "  -  File    : $BinFile"
Write-Log "  -  Size    : $(Format-Bytes $binSize)  ($binSize bytes)"
Write-Log "  -  Ratio   : $([math]::Round((1 - $binSize / $hashSize) * 100, 1))% reduction from source"
Write-Log '  ----------------------------------------------------------------'
Write-Log ''
Write-Log "  Download time : $(Format-Elapsed $dlElapsed)"
Write-Log "  Pack time     : $(Format-Elapsed $packElapsed)"
Write-Log "  Total time    : $(Format-Elapsed ($dlElapsed + $packElapsed))"
Write-Log ''
Write-Log "  Log file      : $script:LogFile"
Write-Log '' -Level SUCCESS
Write-Log "Binary ready: $BinFile" -Level SUCCESS
